# Generated by Django 3.2.4 on 2021-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
