# Generated by Django 3.1.7 on 2021-07-06 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, verbose_name='Page Name')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('Accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('status', models.CharField(max_length=500, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('state', models.PositiveIntegerField(choices=[(0, 'Pending'), (2, 'Accepted'), (1, 'Rejected')], verbose_name='State')),
                ('status', models.CharField(max_length=5000, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
        migrations.CreateModel(
            name='IssuesSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Issue Subject',
                'verbose_name_plural': 'Issue Subjects',
            },
        ),
    ]
