# Generated by Django 3.2.4 on 2021-11-06 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=30, verbose_name='Page Name')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('state', models.CharField(choices=[('pending', 'pending'), ('Accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('status', models.CharField(blank=True, max_length=500, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Appeal',
                'verbose_name_plural': 'Appeals',
            },
        ),
        migrations.CreateModel(
            name='IssuesSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Issue Subject',
                'verbose_name_plural': 'Issue Subjects',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=2000, verbose_name='Description')),
                ('response', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Response')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues_and_requests.issuessubject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
            },
        ),
    ]
