# Generated by Django 3.1.7 on 2021-07-06 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('issues_and_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='orders.order', verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='issue',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='issues_and_requests.issuessubject', verbose_name='Subject'),
        ),
    ]
