# Generated by Django 3.1.7 on 2021-07-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_and_requests', '0003_auto_20210706_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Status'),
        ),
    ]
