# Generated by Django 3.2.4 on 2021-07-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_and_requests', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'Issue', 'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='issuessubject',
            options={'verbose_name': 'Issue Subject', 'verbose_name_plural': 'Issue Subjects'},
        ),
    ]
