# Generated by Django 3.2.4 on 2021-07-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_and_requests', '0008_auto_20210717_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='state',
        ),
    ]
