# Generated by Django 3.1.7 on 2021-07-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=50, verbose_name='ref ID')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('authoriy', models.CharField(max_length=50, verbose_name='Authority')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
