# Generated by Django 3.2.4 on 2021-10-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttransaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'deposit'), (0, 'checkout')], default=0, verbose_name='type'),
        ),
    ]
