# Generated by Django 3.2.4 on 2021-06-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mechan_card',
            field=models.CharField(default='', max_length=16),
        ),
    ]
