# Generated by Django 3.2.4 on 2021-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mechan_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mechan_card',
        ),
        migrations.AddField(
            model_name='user',
            name='merchan_card',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
