# Generated by Django 3.2.4 on 2021-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210710_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_coe',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Referral Code'),
        ),
    ]
