# Generated by Django 3.2.4 on 2021-07-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True, verbose_name='Code')),
                ('date_from', models.DateTimeField(verbose_name='Date from')),
                ('date_to', models.DateTimeField(verbose_name='Date to')),
                ('type', models.CharField(choices=[('percent', 'percent'), ('amount', 'amount')], max_length=20, verbose_name='Coupon type')),
                ('percent', models.PositiveIntegerField(verbose_name='Percent %')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('max_allowed_discount', models.PositiveBigIntegerField(verbose_name='MAx Allowed Discount')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
