# Generated by Django 3.2.4 on 2021-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=15, null=True)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('type', models.CharField(choices=[('percent', 'percent'), ('amount', 'amount')], max_length=20)),
                ('percent', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('max_allowed_discount', models.PositiveBigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
