# Generated by Django 3.1.7 on 2021-07-07 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_allowed_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='MAx Allowed Discount'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Percent %'),
        ),
    ]
