# Generated by Django 3.2.4 on 2021-11-07 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateTimeField(verbose_name='date from')),
                ('date_to', models.DateTimeField(verbose_name='date to')),
                ('fee', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(100)], verbose_name='fee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_promotions', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
        ),
    ]
