# Generated by Django 3.2.4 on 2021-11-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_feepromo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutrequest',
            name='description',
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to=settings.AUTH_USER_MODEL, verbose_name='Applicant'),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='data_accomplished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accomplished date'),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='intendant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intendant_checkouts', to=settings.AUTH_USER_MODEL, verbose_name='Intendant'),
        ),
        migrations.AlterField(
            model_name='checkoutrequest',
            name='status',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='status'),
        ),
    ]
