# Generated by Django 3.2.4 on 2021-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210710_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Balance'),
        ),
    ]
