# Generated by Django 3.2.4 on 2021-11-15 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211115_2039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutrequest',
            old_name='fee',
            new_name='fee_amount',
        ),
        migrations.AddField(
            model_name='checkoutrequest',
            name='fee_percent',
            field=models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='fee percent'),
        ),
    ]
