# Generated by Django 3.2.4 on 2021-11-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211115_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='status',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='status'),
        ),
    ]
