# Generated by Django 3.2.4 on 2021-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210720_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertransaction',
            name='state',
            field=models.CharField(choices=[('pending', 'prepared'), ('committed', 'committed'), ('rollbacked', 'rollbacked'), ('rejected', 'rejected')], default='pending', max_length=20, verbose_name='State'),
        ),
    ]
