# Generated by Django 3.2.4 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_checkoutrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutrequest',
            name='fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Fee amount'),
        ),
    ]
