# Generated by Django 3.2.4 on 2021-11-06 20:17

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import shops.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(null=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(null=True, verbose_name='slug')),
                ('description', models.CharField(max_length=5000, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='Name')),
                ('free_delivery', models.BooleanField(blank=True, default=False, verbose_name='Free Delivery')),
                ('description', models.CharField(blank=True, max_length=5000, null=True, verbose_name='product description')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Price')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('last_update', models.DateTimeField(auto_now=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords')),
                ('attrs', models.JSONField(default=dict, verbose_name='attributes')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shops.models.ProductImage.generate_path)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Name')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('shop_phone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[0-9]*$')], verbose_name='cell phone')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Address')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=shops.models.Shop.generate_path, verbose_name='Logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=shops.models.Shop.generate_path, verbose_name='Banner')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('post_destinations', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Postal Destinations')),
                ('convers_all_states', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Name')),
                ('has_color', models.BooleanField(default=True)),
                ('has_size', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(related_name='types', to='shops.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('categories', models.ManyToManyField(related_name='subtypes', to='shops.Category', verbose_name='Categories')),
                ('types', models.ManyToManyField(related_name='subtypes', to='shops.Type', verbose_name='Types')),
            ],
            options={
                'verbose_name': 'SubType',
                'verbose_name_plural': 'SubTypes',
            },
        ),
    ]
