# Generated by Django 3.2.4 on 2021-11-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='max_num_of_products',
            field=models.PositiveIntegerField(default=100, verbose_name='#Max Allowed Product'),
        ),
    ]
