# Generated by Django 3.2.4 on 2021-06-30 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
