# Generated by Django 3.2.4 on 2021-06-30 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_shop_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
