# Generated by Django 3.2.4 on 2021-10-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_alter_product_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attrs',
            field=models.JSONField(default={}, verbose_name='attributes'),
        ),
    ]
