# Generated by Django 3.1.7 on 2021-07-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_remove_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cell phone'),
        ),
        migrations.AddField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='post_destinatinos',
            field=models.CharField(max_length=1000, null=True, verbose_name='Postal Destinations'),
        ),
    ]
