# Generated by Django 3.2.4 on 2021-11-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_alter_product_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='type',
            name='description',
        ),
        migrations.RemoveField(
            model_name='type',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subtype',
            name='categories',
            field=models.ManyToManyField(related_name='subtypes', to='shops.Category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='subtype',
            name='types',
            field=models.ManyToManyField(related_name='subtypes', to='shops.Type', verbose_name='Types'),
        ),
    ]
