# Generated by Django 3.2.4 on 2021-11-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_auto_20211102_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='product description'),
        ),
    ]
