# Generated by Django 3.2.4 on 2021-11-04 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_attributes', '0001_initial'),
        ('shops', '0009_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product_attributes.Color', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(blank=True, default=False, verbose_name='Free Delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product_attributes.Size', verbose_name='Sizes'),
        ),
    ]
