# Generated by Django 3.2.4 on 2021-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_alter_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attrs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Keywords'),
        ),
    ]
