# Generated by Django 3.2.4 on 2021-07-13 16:19

from django.db import migrations
import django_resized.forms
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20210713_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[240, 360], upload_to=shops.models.Product.generate_path, verbose_name='image'),
        ),
    ]
