# Generated by Django 3.2.4 on 2021-11-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_attributes', '0001_initial'),
        ('shops', '0011_auto_20211104_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='products', to='product_attributes.Color', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='product_attributes.Size', verbose_name='Sizes'),
        ),
    ]
