# Generated by Django 3.2.4 on 2021-07-13 16:34

from django.db import migrations
import django_resized.forms
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[360, 240], upload_to=shops.models.Product.generate_path, verbose_name='image'),
        ),
    ]
