# Generated by Django 3.2.4 on 2021-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0012_auto_20211104_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(max_length=5000, verbose_name='description')),
                ('products', models.ManyToManyField(related_name='collections', to='shops.Product', verbose_name='products')),
            ],
        ),
    ]
