# Generated by Django 3.2.4 on 2021-11-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='collection',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='slug'),
        ),
    ]
