# Generated by Django 3.2.4 on 2021-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0013_auto_20210718_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='shops.Category', verbose_name='Categories'),
        ),
    ]
