# Generated by Django 3.2.4 on 2021-11-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0014_auto_20211106_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='slug',
            field=models.SlugField(null=True, verbose_name='slug'),
        ),
    ]
