# Generated by Django 3.2.4 on 2021-07-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_attributes', '0002_auto_20210710_1107'),
        ('shops', '0014_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='product_attributes.Color', verbose_name='Colors'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(related_name='products', to='product_attributes.Size', verbose_name='Sizes'),
        ),
    ]
