# Generated by Django 3.2.4 on 2021-09-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20210718_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='post_destinatinos',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Postal Destinations'),
        ),
    ]
