# Generated by Django 3.2.4 on 2021-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0016_alter_shop_post_destinatinos'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='convers_all_states',
            field=models.BooleanField(default=False),
        ),
    ]
