# Generated by Django 3.2.4 on 2021-09-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0018_alter_shop_convers_all_states'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='post_destinatinos',
            new_name='post_destinations',
        ),
    ]
