# Generated by Django 3.2.4 on 2021-10-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_rename_post_destinatinos_shop_post_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_delivery',
            field=models.BooleanField(default=False, verbose_name='Free Delivery'),
        ),
    ]
