# Generated by Django 3.2.4 on 2021-10-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_product_free_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='has_color',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='has_size',
            field=models.BooleanField(default=True),
        ),
    ]
