# Generated by Django 3.2.4 on 2021-10-03 15:46

from django.db import migrations
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_auto_20211002_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attrs',
            field=shops.models.OldJSONField(blank=True, default=dict),
        ),
    ]
