# Generated by Django 3.2.4 on 2021-10-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_alter_product_attrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attrs',
        ),
        migrations.RemoveField(
            model_name='type',
            name='atrrs',
        ),
    ]
