# Generated by Django 3.1.7 on 2021-07-09 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, 'Success'), (1, 'Warning'), (2, 'Error'), (3, 'Info')], verbose_name='Level')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('body', models.CharField(blank=True, max_length=5000, verbose_name='Body')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved_messages', to=settings.AUTH_USER_MODEL, verbose_name='Reciever')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Admin message',
                'verbose_name_plural': 'Admin messages',
            },
        ),
    ]
