# Generated by Django 3.2.4 on 2021-10-04 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(0, 'Success'), (1, 'Warning'), (2, 'Error'), (3, 'Info')], verbose_name='Level')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('body', models.CharField(blank=True, max_length=5000, verbose_name='Body')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Admin message',
                'verbose_name_plural': 'Admin messages',
            },
        ),
    ]
