# Generated by Django 3.2.4 on 2021-07-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_adminmessage_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
