# Generated by Django 3.2.4 on 2021-11-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_adminmessage_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessage',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='adminmessage',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'unread'), (1, 'read')], default=0, verbose_name='status'),
        ),
    ]
