# Generated by Django 3.2.4 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_adminmessage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmessage',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'read'), (0, 'unread')], default=0, verbose_name='status'),
        ),
    ]
