# Generated by Django 3.2.4 on 2021-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincesandcities',
            name='cities',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='provincesandcities',
            name='provinces',
            field=models.JSONField(),
        ),
    ]
