# Generated by Django 3.2.4 on 2021-07-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210712_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProvincesAndCities',
        ),
    ]
