# Generated by Django 3.2.4 on 2021-06-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
        ('coupons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_alter_appeal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discounted_total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('tracking_code', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('accept', 'accept'), ('rejected', 'rejected'), ('sent', 'sent'), ('received', 'recieved'), ('cancelled', 'cancelled'), ('returned', 'returned')], default='pending', max_length=20)),
                ('verify_sent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=11)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('posta_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price_after_discount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('total_price_after_applying_coupon', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('use_default_address', models.BooleanField(default=True)),
                ('post_method', models.CharField(choices=[('ultimate', 'ultimate'), ('express', 'express'), ('normal', 'normal')], default='ultimate', max_length=20)),
                ('Address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderaddress')),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('has_discount', models.BooleanField(default=False)),
                ('discounted_price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('discounted_total_price', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shops.color')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discounts.discount')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shops.size')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.orderlist'),
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='shops.shop'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
