# Generated by Django 3.2.4 on 2021-06-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='total_price_after_applying_coupon',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='total_price_after_discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
