# Generated by Django 3.2.4 on 2021-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_tracking_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_code_status',
            field=models.CharField(default='در انتظار تاییدمث', max_length=500, verbose_name='tracking Status'),
        ),
    ]
