# Generated by Django 3.2.4 on 2021-07-18 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_alter_discount_id'),
        ('orders', '0005_alter_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='discounts.discount', verbose_name='Discount'),
        ),
    ]
