# Generated by Django 3.2.4 on 2021-07-20 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='has_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='date_accomplished',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Accomplished date'),
        ),
    ]
