# Generated by Django 3.2.4 on 2021-07-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210720_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code_status',
            field=models.CharField(default='', max_length=500, verbose_name='tracking Status'),
        ),
    ]
