# Generated by Django 3.2.4 on 2021-09-23 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0015_auto_20210718_2246'),
        ('orders', '0009_order_tracking_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shops.product', verbose_name='Product'),
        ),
    ]
